### PR TITLE
Build out the homepage

### PR DESCRIPTION
**Pull request by cigwe416**
#### Screenshots (if appropriate)

Screenshot 2020-04-13 at 17 02 11
Screenshot 2020-04-13 at 17 02 22

Screenshot 2020-04-13 at 17 02 47
Screenshot 2020-04-13 at 17 03 18

Screenshot 2020-04-13 at 17 03 32
Screenshot 2020-04-13 at 17 03 42

### CODE REVIEW

**Comment by cigwe416** [comment]
> How come the check in and check out button are on the landing page where it also says `request a demo`?

I'll check that out with Kehinde.

**Comment by cigwe416** [comment]
> How come the check in and check out button are on the landing page where it also says `request a demo`?

@todueke415 ,I think its just a design concept from Kehinde. What do you think about it and how do you think it can be? We can easily change or remove the `Request a demo` text.

**Comment by todueke415** [comment]
Ye

> > How come the check in and check out button are on the landing page where it also says `request a demo`?
> 
> @todueke415 ,I think its just a design concept from Kehinde. What do you think about it and how do you think it should be? We can easily change or remove the `Request a demo` text.

yes I think it should be removed because it could be a bit misleading

**Comment by ibashir398** [comment]
@cigwe416 so i don't think this new design have been shared with me. i will like to go through them before going deep as to implementation. content wise, just a minor one, i think we should avoid mixing concept, SMV means smart visitor management, the use if 'Efficient visitor management' doesn't speak to the APP name.

**Comment by cigwe416** [comment]
> @cigwe416 so i don't think this new design have been shared with me. i will like to go through them before going deep as to implementation. content wise, just a minor one, i think we should avoid mixing concept, SMV means smart visitor management, the use if 'Efficient visitor management' doesn't speak to the APP name.

@ibashir398  I'll engage Kehinde to share with you the new design, I thought that had already been done.

**Comment by ibashir398** [comment]
OK that's fine. Good job @cigwe416, please effect the changes.

**Comment by cigwe416** [comment]
> Nice work @cigwe416. This looks so clean and beautiful, However the page is not **responsive**. I strongly believe it is best we start with responsiveness as it is alway hard(hacky) to fix code to be responsive after it has been developed.

okay. nice observation. However, the screens for mobile are not yet available. reason I could not include it here

**Comment by ikelani421** [comment]
> > Nice work @cigwe416. This looks so clean and beautiful, However the page is not **responsive**. I strongly believe it is best we start with responsiveness as it is alway hard(hacky) to fix code to be responsive after it has been developed.
> 
> okay. nice observation. However, the screens for mobile are not yet available. reason I could not include it here

**Comment by ikelani421** [comment]
> > > Nice work @cigwe416. This looks so clean and beautiful, However the page is not **responsive**. I strongly believe it is best we start with responsiveness as it is alway hard(hacky) to fix code to be responsive after it has been developed.
> > 
> > 
> > okay. nice observation. However, the screens for mobile are not yet available. reason I could not include it here

Okay, You are right, the screens are not available, We should talk to Kenny about it and still add the responsiveness on this PR. i will give Kenny a call now.

**Pull request merged**
